### ISSUE TITLE
{'captcha_key': ['invalid-response'], 'captcha_sitekey': '4c672d35-0701-42b2-88c3-78380b0db560', 'captcha_service': 'hcaptcha'}

### ISSUE THREAD

**Issue by iagoStorm** [anhonor/TokenCreator#1]
the signup variable returns a error, I tried change my proxies, use both capmonster and capsolver but nothing work. Can someone help me?
![Screenshot_7](https://github.com/anhonor/TokenCreator/assets/108151364/eb3cff68-848d-4c55-9836-ad41c32fdb7d)

**Comment by anhonor** [comment]
This is an issue regarding Capmonster and Capsolver. They're both flagged at the moment. It is not my responsibility whatsoever. I will be debugging everything In the future, please be patient.
