### ISSUE TITLE
EMAIL NOT CREATE

### ISSUE THREAD

**Issue by King-Anoz** [anhonor/TokenCreator#2]
←[94m*←[0m Retrieved Clearence (dbzscZATyuKI8At2WDmDJJ0zr.Hc8KXlisFM1TguY5g-1708391324-1.0-AVvJv7+2ba4gCoTNH22v7nIrh6KNc5IfCOgsVMOZiLSBGetHT2+ZR/M+fjlX5B3IOCCi266O8vmgiW7I59QA8QY=)
←[31m*←[0m Mailmask Not Created: wzrpxja@puabook.com

**Comment by anhonor** [comment]
happens often, will get fixed in a day or two. the site, mailmasker.com, is being abused by you guys too often. i can expect a patch coming soon.

tl;dr
will get fixed by them eventually.
