### ISSUE TITLE
error with capsolver

### ISSUE THREAD

**Issue by Eblan4ikRK** [anhonor/TokenCreator#6]
* Token Not Created: {'captcha_key': ['captcha-required'], 'captcha_sitekey': '4c672d35-0701-42b2-88c3-78380b0db560', 'captcha_service': 'hcaptcha'}
*

**Comment by anhonor** [comment]
unfortunately there's a problem regarding capsolver, capmonster, or any public captcha solving apis.. all captcha responses are flagged.
